# Generated by Django 6.0.7 on 2026-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyectos', '0002_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=5),
        ),
    ]
