# Generated by Django 6.0.7 on 2026-08-31 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyectos', '0003_alter_tarea_prioridad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='duracion',
            new_name='duarcion',
        ),
    ]
