# Generated by Django 6.0.7 on 2026-08-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyectos', '0004_rename_duracion_proyecto_duarcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='duarcion',
            new_name='duracion',
        ),
    ]
